theme: jekyll-theme-slate

title: DDPR
description: Template Docker + Django + PostgreSQL + React setup.

github:
  repository_url: https://github.com/kirillzhosul/ddpr
  owner_url: https://kirillzhosul.site
  owner_name: kirillzhosul
  zip_url: https://github.com/kirillzhosul/ddpr/zipball/main
  tar_url: https://github.com/kirillzhosul/ddpr/tarball/main
  is_project_page: true
  
show_downloads: true
