theme: jekyll-theme-slate

title: DDPR
description: Template Docker + Django + PostgreSQL + React setup.

github:
  repository_url: https://github.com/kirillzhosul/ddpr
  owner_url: https://kirillzhosul.site
  owner_name: kirillzhosul
  branch: main

show_downloads: true
